### ISSUE TITLE
Google OAuth

### ISSUE THREAD

**Issue by RafaelCenzano** [alpha-phi-omega-ez/apoez.org-flask#5]
Theoretically, the code should work for Google OAuth but in practice, google is returning a `Error 400: redirect_uri_mismatch`. This error occurs typically when the callback uri is not in the allowedlist. The given callback uri is given in the allowedlist in Gcloud credentials but still fails to work.

**Comment by RafaelCenzano** [comment]
https://developers.google.com/identity/protocols/oauth2/web-server#authorization-errors-redirect-uri-mismatch

**Comment by delexagon** [comment]
I'm not certain that this is the problem that you are experiencing, but if your redirect uri according to Google is http://127.0.0.1:8000/login/callback, rather than http://localhost:8000/login/callback (which is what our website returns), Google will throw this error. After I changed that, I no longer got the error.

**Comment by delexagon** [comment]
After that I got a 'requires https' error, which idk if you've managed your way past that but it'll be a pain to set up if you haven't

**Comment by jadbaibai** [comment]
:(
